spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: emp-route
          uri: ${EMP_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/emp/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Powered-By, WpfeiffeGateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
        - id: team-route
          uri: ${TEAM_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/team/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Powered-By, WpfeiffeGateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
